# Generated by Django 3.0.7 on 2020-06-19 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_tittle', models.CharField(max_length=200)),
                ('wish_description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 15, 34, 384247, tzinfo=utc))),
            ],
        ),
    ]
