# Generated by Django 3.0.7 on 2020-06-26 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20200626_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 58, 51, 741987)),
        ),
    ]
