# Generated by Django 3.0.7 on 2020-06-30 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wish', '0006_auto_20200627_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishes',
            name='completed',
            field=models.ImageField(blank=True, upload_to='css/img'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 21, 47, 11, 165184)),
        ),
    ]
