# Generated by Django 3.0.7 on 2020-06-30 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0007_auto_20200630_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 21, 47, 20, 197784)),
        ),
    ]
