# Generated by Django 3.0.7 on 2020-07-02 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0008_auto_20200630_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishes',
            options={'verbose_name_plural': 'wish'},
        ),
        migrations.AlterField(
            model_name='wishes',
            name='completed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 20, 22, 16, 64874)),
        ),
    ]
